dotCMS/core#19089 template listing changes.
dotCMS/dotcms-webcomponents pull request #42
Opened 2020-12-02 19:38 UTC by hmoreras

- Change the input of `dot-state-icon` to a more generic interface

2020-12-03 13:34 UTC, fmontes requested changes

2020-12-03 13:34 UTC, fmontes commented on src/elements/dot-state-icon/dot-state-icon.e2e.ts
> +import { newE2EPage } from '@stencil/core/testing';
Missing tests?

2020-12-03 13:34 UTC, fmontes commented on src/elements/dot-state-icon/dot-state-icon.tsx
> +        if (live === 'true' || live == true) {
A lots of "ors" here.

What about 

```typescript
function isTrue(val: string | boolean): boolean {
    return val === 'true' || val == true
}

```
```suggestion
        if (isTrue(live)) {
```

2020-12-03 15:09 UTC, alfredo-dotcms commented on src/elements/dot-state-icon/dot-state-icon.tsx
> +        if (live === 'true' || live == true) {
or you could **do cast to string** at the beginning of the method, and leave everything as is!

2020-12-03 16:03 UTC, ivorpad commented on src/elements/dot-state-icon/dot-state-icon.tsx
> +        if (live === 'true' || live == true) {
`const isTrue = (val: string | bool) => JSON.parse(val)`

2020-12-07 22:39 UTC, fmontes requested changes

2020-12-07 22:39 UTC, fmontes commented on src/elements/dot-contentlet-icon/dot-contentlet-icon.e2e.ts
> +                console.log('beto', element.outerHTML);
remove

2020-12-07 22:39 UTC, fmontes commented on src/elements/dot-contentlet-icon/dot-contentlet-icon.e2e.ts
> +                console.log('materialIcon', materialIcon.outerHTML);
remove

2020-12-07 22:39 UTC, fmontes commented on src/elements/dot-contentlet-lock-icon/dot-contentlet-lock-icon.tsx
> +                <mwc-icon>{this.locked === true ? 'locked' : 'lock_open'}</mwc-icon>
```suggestion
                <mwc-icon>{this.locked ? 'locked' : 'lock_open'}</mwc-icon>
```

2020-12-07 22:39 UTC, fmontes commented on src/elements/dot-state-icon/dot-state-icon.e2e.ts
> +        expect(await tooltip.getProperty('content')).toEqual('Archived');
Why don't you assert the `textContent` or `innerHtml` of the element here?

2020-12-08 15:33 UTC, hmoreras commented on src/elements/dot-state-icon/dot-state-icon.e2e.ts
> +        expect(await tooltip.getProperty('content')).toEqual('Archived');
because that is part of the test in the tooltip, here what I care is that I pass the correct value.

2020-12-08 16:39 UTC, merged