Added a new outputTarget to support tree shakable components and upgr…
dotCMS/dotcms-webcomponents pull request #46
Opened 2021-01-11 19:57 UTC by ivorpad

…aded the dependencies

2021-01-11 20:28 UTC, fmontes requested changes

2021-01-11 20:28 UTC, fmontes commented on package.json
> +    "module": "./dist/custom-elements/index.js",
Why?

2021-01-11 20:28 UTC, fmontes commented on package.json
> +        "@stencil/core": "^2.3.0",
Did you try to run the tests?

2021-01-11 20:28 UTC, fmontes commented on package.json
> +        "@storybook/addon-actions": "^6.1.11",
Did you try storybook?

2021-01-11 20:28 UTC, fmontes commented on package.json
> +        "@tarekraafat/autocomplete.js": "^8.2.1",
Did you check where all this components are used?

2021-01-11 21:06 UTC, ivorpad commented on package.json
> +    "module": "./dist/custom-elements/index.js",
Stencil.js build script recommendation.

2021-01-11 22:09 UTC, ivorpad commented on package.json
> +        "@stencil/core": "^2.3.0",
Yes

2021-01-11 22:09 UTC, ivorpad commented on package.json
> +        "@storybook/addon-actions": "^6.1.11",
Yes

2021-01-11 22:27 UTC, alfredo-dotcms approved these changes

2021-01-11 22:47 UTC, ivorpad commented on package.json
> +        "@tarekraafat/autocomplete.js": "^8.2.1",
Yes

2025-08-07 15:47 UTC, sfreudenthaler commented
stale

2025-08-07 15:48 UTC, closed without merging