Issue 19592 create component that preview material icons v3
dotCMS/dotcms-webcomponents pull request #49
Opened 2021-02-04 18:59 UTC by alfredo-dotcms

preview icon selected added and component name rename

2021-02-04 21:53 UTC, ivorpad approved these changes

2021-02-05 16:50 UTC, fmontes requested changes

2021-02-05 16:50 UTC, fmontes commented on src/elements/dot-material-icon-picker/dot-material-icon-picker.tsx
>              <div class="dot-material-icon">
If you need a wrapper you might want to use `<Host>`

2021-02-05 17:07 UTC, hmoreras requested changes

2021-02-05 17:07 UTC, hmoreras commented on src/elements/dot-material-icon-picker/dot-material-icon-picker.tsx
> +                        style={{ color: this.colorValue || '#000' }}
is needed the `or` since `#000` is already the default value ?

2021-02-08 21:20 UTC, fmontes requested changes

2021-02-08 21:20 UTC, fmontes commented on src/elements/dot-material-icon-picker/dot-material-icon-picker.scss
> +.dot-material-icon_select-input {
```suggestion
.dot-material-icon__select-input {
```

2021-02-08 21:20 UTC, fmontes commented on src/elements/dot-material-icon-picker/dot-material-icon-picker.scss
>      margin-right: 8px;
You can use `em` everywhere since the font-size is configurable.

2021-02-08 21:45 UTC, ivorpad approved these changes

2021-02-12 16:52 UTC, fmontes approved these changes

2021-02-12 16:53 UTC, merged