dotCMS/core#19933 fix Add-icon-selector-in-tools-portlet
dotCMS/dotcms-webcomponents pull request #51
Opened 2021-02-17 20:49 UTC by alfredo-dotcms

2021-02-17 21:09 UTC, ivorpad commented on src/elements/dot-material-icon-picker/dot-material-icon-picker.scss
> +    max-height: 20em;
`rem` is preferred as `em` is relative to its nearest parent

2021-02-17 21:10 UTC, ivorpad commented on src/elements/dot-material-icon-picker/dot-material-icon-picker.scss
> +    top: calc(1em + 8px);
Why use `calc`here? You can use just `rem` without the calc CSS function.

2021-02-17 21:12 UTC, alfredo-dotcms commented on src/elements/dot-material-icon-picker/dot-material-icon-picker.scss
> +    max-height: 20em;
since this component use size as an input
https://github.com/dotCMS/dotcms-webcomponents/blob/14ccea968138e0d04ec0de42e0754369ca7ff5fb/src/elements/dot-material-icon-picker/dot-material-icon-picker.tsx#L38

everything needs to be in proportion of his parent and not the document

2021-02-17 21:13 UTC, alfredo-dotcms commented on src/elements/dot-material-icon-picker/dot-material-icon-picker.scss
> +    top: calc(1em + 8px);
only using 1em does not put the options box in the right position, so we need to add 8px to complete space of borders

2021-02-17 21:16 UTC, fmontes requested changes

2021-02-17 21:16 UTC, fmontes commented on src/elements/dot-material-icon-picker/dot-material-icon-picker.scss
> +    max-height: calc(1em + 8px);
Why 8?

2021-02-17 21:17 UTC, alfredo-dotcms commented on src/elements/dot-material-icon-picker/dot-material-icon-picker.scss
> +    max-height: calc(1em + 8px);
https://github.com/dotCMS/dotcms-webcomponents/pull/51#discussion_r577948428

2021-02-18 15:58 UTC, fmontes commented on src/elements/dot-material-icon-picker/dot-material-icon-picker.scss
> +    top: calc(1em + 8px);
Can we do something more "reponsive" here? Maybe flexbox? something that doesn't required such a fit math?

2021-02-18 17:39 UTC, fmontes approved these changes

2021-02-18 17:41 UTC, fmontes approved these changes

2021-02-18 17:41 UTC, fmontes commented on src/elements/dot-material-icon-picker/dot-material-icon-picker.tsx
> +                                this.getSuggestionElement(suggestion)
Let's stop doing this, we should create components.

2021-02-19 14:59 UTC, fmontes approved these changes

2021-02-19 15:28 UTC, merged